name: My First Action

on:
  workflow_dispatch: # allows manual run
  push:              # triggers on new pushes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2005664@ds.study.iitm.ac.in
        run: echo "Hello, world!"
